DROP TABLE IF EXISTS TEST2567_ENTITY;

CREATE TABLE TEST2567_ENTITY (
    SALESORDERNUMBER    VARCHAR (10)    NULL, 
    SEQNO               VARCHAR (3)     NULL, 
    LINEITEM            VARCHAR (2)     NULL, 
    PARTID              VARCHAR (32)    NULL, 
    PARTNAME            VARCHAR (29)    NULL, 
    PARTVERSION         VARCHAR (3)     NULL, 
    ORIGDATEREQD        DATE            NULL, 
    CURDATEREQD         DATE            NULL, 
    CUSTOMERNAME        VARCHAR (30)    NULL, 
    CUSTORDERNUMBER     VARCHAR (20)    NULL, 
    ORDERSTATE          VARCHAR (1)     NULL, 
    DATECREATED         DATE            NULL, 
    DATECHANGED         DATE            NULL, 
    ORIGQTYREQD         FLOAT           NULL, 
    CUSTOMERQTYREQD     FLOAT           NULL, 
    CURQTYREQD          FLOAT           NULL, 
    PRICEPERPART        FLOAT           NULL, 
    QTYSHIPPED          FLOAT           NULL, 
    LOADDATE            DATE            NULL
);

Insert into TEST2567_ENTITY (
SALESORDERNUMBER, SEQNO, LINEITEM, PARTID, PARTNAME, PARTVERSION,
ORIGDATEREQD, CURDATEREQD, CUSTOMERNAME, CUSTORDERNUMBER, ORDERSTATE,
DATECREATED, DATECHANGED, ORIGQTYREQD, CUSTOMERQTYREQD, CURQTYREQD,
PRICEPERPART, QTYSHIPPED, LOADDATE
) values (
'EM71130021', '001', '01', 'PART-30021', 'PART-30021', null,
'2005-01-03', '2005-01-03', 'EXTERN', '12701', 'B',
'2003-08-04', '2004-04-27', 0, 0, 12701,
0, 0, '2004-04-26'
);
