DROP TABLE test1355_country CASCADE CONSTRAINTS
/
DROP TABLE test1355_state_prov CASCADE CONSTRAINTS
/
DROP TABLE test1355_city CASCADE CONSTRAINTS
/
DROP TABLE test1355_golf_course CASCADE CONSTRAINTS
/
DROP TABLE test1355_golf_course_tees CASCADE CONSTRAINTS
/
DROP TABLE test1355_golf_course_holes CASCADE CONSTRAINTS
/
