DROP TABLE test31_relation CASCADE CONSTRAINTS
/
DROP TABLE test31_extends2 CASCADE CONSTRAINTS
/
DROP TABLE test31_extends1 CASCADE CONSTRAINTS
/
DROP TABLE test31_related CASCADE CONSTRAINTS
/
DROP TABLE test31_persistent CASCADE CONSTRAINTS
/
DROP TABLE test31_group CASCADE CONSTRAINTS
/
