/* Generated By:JavaCC: Do not edit this line. DTDInitialParserConstants.java */
package org.exolab.castor.xml.dtd.parser;

public interface DTDInitialParserConstants {

  int EOF = 0;
  int LETTER = 1;
  int DIGIT = 2;
  int COMBINING_CHAR = 3;
  int EXTENDER = 4;
  int NAMECHAR = 5;
  int NAME = 6;
  int S = 7;
  int TEXT_UNIT = 8;
  int BEGIN_PE_DECL = 9;
  int PE_REFERENCE_D = 10;
  int NAME_OF_PE = 11;
  int SPACE = 12;
  int START_DQ = 13;
  int START_SQ = 14;
  int END_PE_DECL = 15;
  int ENTITY_VALUE_TEXT_DQ = 16;
  int PE_REFERENCE_DQ = 17;
  int END_DQ = 18;
  int ENTITY_VALUE_TEXT_SQ = 19;
  int PE_REFERENCE_SQ = 20;
  int END_SQ = 21;

  int DEFAULT = 0;
  int WithinPEdecl = 1;
  int WithinEntityValueDQ = 2;
  int WithinEntityValueSQ = 3;

  String[] tokenImage = {
    "<EOF>",
    "<LETTER>",
    "<DIGIT>",
    "<COMBINING_CHAR>",
    "<EXTENDER>",
    "<NAMECHAR>",
    "<NAME>",
    "<S>",
    "<TEXT_UNIT>",
    "<BEGIN_PE_DECL>",
    "<PE_REFERENCE_D>",
    "<NAME_OF_PE>",
    "<SPACE>",
    "\"\\\"\"",
    "\"\\\'\"",
    "\">\"",
    "<ENTITY_VALUE_TEXT_DQ>",
    "<PE_REFERENCE_DQ>",
    "\"\\\"\"",
    "<ENTITY_VALUE_TEXT_SQ>",
    "<PE_REFERENCE_SQ>",
    "\"\\\'\"",
  };

}
