DROP TABLE test87_entity CASCADE CONSTRAINTS
/
DROP TABLE test87_product CASCADE CONSTRAINTS
/
DROP TABLE test87_group CASCADE CONSTRAINTS
/
DROP TABLE test87_extended CASCADE CONSTRAINTS
/
DROP TABLE test87_base CASCADE CONSTRAINTS
/
