CREATE TABLE test2763_book (
    id INTEGER PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    ts INTEGER NOT NULL
)
go

CREATE TABLE test2763_employee (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL
)
go