DROP TABLE TEST1206_STATE CASCADE CONSTRAINTS;

DROP TABLE TEST1206_COUNTRY CASCADE CONSTRAINTS;

CREATE TABLE TEST1206_COUNTRY (
    OID VARCHAR(8) NOT NULL,
    NAME VARCHAR(60) NOT NULL
);

ALTER TABLE TEST1206_COUNTRY ADD PRIMARY KEY (OID);

CREATE TABLE TEST1206_STATE (
    OID VARCHAR(8) NOT NULL,
    NAME VARCHAR(60) NOT NULL,
    COUNTRY VARCHAR(8) NOT NULL
);

ALTER TABLE TEST1206_STATE ADD PRIMARY KEY (OID);

ALTER TABLE TEST1206_STATE ADD FOREIGN KEY (COUNTRY)
REFERENCES TEST1206_COUNTRY (OID);
