/*
 * This file generated by the ExoLab XML Schema Compiler
 * Compiler Version: 1.0 alpha (19990929)
 * Date generated: Tue Oct 05 12:26:51 PDT 1999
 */

package org.exolab.castor.builder;

// Sax imports
import org.xml.sax.*;
import org.exolab.castor.xml.*;

// Java imports
import java.io.Reader;

/**
 *
**/
public class StringUnmarshaller extends HandlerBase {

  
    private StringBuffer sb = null;
    Resolver _resolver = null;
    
    public StringUnmarshaller() {
        super();
        sb = new StringBuffer();
    }

    public String getString() {
        return sb.toString();
    }
    
    public void setResolver(Resolver resolver) {
        _resolver = resolver;
    } //-- setResolver
    
    /* SAX Methods */
    
    public void characters(char[] ch, int start, int length) 
        throws SAXException
    {
        sb.append(ch, start, length);
    }

}
