DROP TABLE test1196_state CASCADE CONSTRAINTS
/
DROP TABLE test1196_country CASCADE CONSTRAINTS
/
DROP TABLE test1196_car CASCADE CONSTRAINTS
/
DROP TABLE test1196_driver CASCADE CONSTRAINTS
/
DROP TABLE test1196_computer CASCADE CONSTRAINTS
/
DROP TABLE test1196_orderitem CASCADE CONSTRAINTS
/
DROP TABLE test1196_product CASCADE CONSTRAINTS
/
DROP TABLE test1196_order CASCADE CONSTRAINTS
/
