DROP TABLE TEST1196_STATE CASCADE CONSTRAINTS
/
DROP TABLE TEST1196_COUNTRY CASCADE CONSTRAINTS
/
DROP TABLE TEST1196_CAR CASCADE CONSTRAINTS
/
DROP TABLE TEST1196_DRIVER CASCADE CONSTRAINTS
/
DROP TABLE TEST1196_COMPUTER CASCADE CONSTRAINTS
/
DROP TABLE TEST1196_ORDERITEM CASCADE CONSTRAINTS
/
DROP TABLE TEST1196_PRODUCT CASCADE CONSTRAINTS
/
DROP TABLE TEST1196_ORDER CASCADE CONSTRAINTS
/
