DROP TABLE TEST1206_STATE
GO

DROP TABLE TEST1206_COUNTRY
GO

CREATE TABLE TEST1206_COUNTRY(
	OID varchar(8) NOT NULL,
	NAME varchar(60) NOT NULL,
PRIMARY KEY ( OID )
)
GO

CREATE TABLE TEST1206_STATE(
	OID varchar(8) NOT NULL,
	NAME varchar(60) NOT NULL,
	COUNTRY varchar(8) NOT NULL,
PRIMARY KEY ( OID ) 
)
GO
ALTER TABLE TEST1206_STATE 
ADD FOREIGN KEY(COUNTRY)
REFERENCES TEST1206_COUNTRY (OID)
GO
