drop table  test94_poly_car;
drop table  test94_poly_computer;
drop table  test94_poly_laptop;
drop table  test94_poly_ordr;
drop table  test94_poly_owner;
drop table  test94_poly_prod;
drop table  test94_poly_order_product;
drop table  test94_poly_detail;
drop table  test94_poly_truck;
