CREATE TABLE test81_test_depends_ns (
  id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
  master_id int,
  descrip varchar(50) default ''
);

CREATE TABLE test81_test_master_ns (
  id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
  descrip varchar(50) default ''
);