DROP TABLE test3065_extended CASCADE CONSTRAINTS
/
DROP TABLE test3065_extended2 CASCADE CONSTRAINTS
/
DROP TABLE test3065_extendedextended CASCADE CONSTRAINTS
/
DROP TABLE test3065_object CASCADE CONSTRAINTS
/
