CREATE TABLE TEST2567_ENTITY (
    SALESORDERNUMBER    VARCHAR (10), 
    SEQNO               VARCHAR (3), 
    LINEITEM            VARCHAR (2), 
    PARTID              VARCHAR (32), 
    PARTNAME            VARCHAR (29), 
    PARTVERSION         VARCHAR (3), 
    ORIGDATEREQD        DATE, 
    CURDATEREQD         DATE, 
    CUSTOMERNAME        VARCHAR (30), 
    CUSTORDERNUMBER     VARCHAR (20), 
    ORDERSTATE          VARCHAR (1), 
    DATECREATED         DATE, 
    DATECHANGED         DATE, 
    ORIGQTYREQD         FLOAT, 
    CUSTOMERQTYREQD     FLOAT, 
    CURQTYREQD          FLOAT, 
    PRICEPERPART        FLOAT, 
    QTYSHIPPED          FLOAT, 
    LOADDATE            DATE
);

Insert into TEST2567_ENTITY (
SALESORDERNUMBER, SEQNO, LINEITEM, PARTID, PARTNAME, PARTVERSION,
ORIGDATEREQD, CURDATEREQD, CUSTOMERNAME, CUSTORDERNUMBER, ORDERSTATE,
DATECREATED, DATECHANGED, ORIGQTYREQD, CUSTOMERQTYREQD, CURQTYREQD,
PRICEPERPART, QTYSHIPPED, LOADDATE
) values (
'EM71130021', '001', '01', 'PART-30021', 'PART-30021', null,
'2005-01-03', '2005-01-03', 'EXTERN', '12701', 'B',
'2003-08-04', '2004-04-27', 0, 0, 12701,
0, 0, '2004-04-26'
);
