DROP TABLE TEST2567_ENTITY CASCADE CONSTRAINTS;

CREATE TABLE TEST2567_ENTITY (
    SALESORDERNUMBER    VARCHAR2 (10)    NULL, 
    SEQNO               VARCHAR2 (3)     NULL, 
    LINEITEM            VARCHAR2 (2)     NULL, 
    PARTID              VARCHAR2 (32)    NULL, 
    PARTNAME            VARCHAR2 (29)    NULL, 
    PARTVERSION         VARCHAR2 (3)     NULL, 
    ORIGDATEREQD        DATE             NULL, 
    CURDATEREQD         DATE             NULL, 
    CUSTOMERNAME        VARCHAR2 (30)    NULL, 
    CUSTORDERNUMBER     VARCHAR2 (20)    NULL, 
    ORDERSTATE          VARCHAR2 (1)     NULL, 
    DATECREATED         DATE             NULL, 
    DATECHANGED         DATE             NULL, 
    ORIGQTYREQD         FLOAT            NULL, 
    CUSTOMERQTYREQD     FLOAT            NULL, 
    CURQTYREQD          FLOAT            NULL, 
    PRICEPERPART        FLOAT            NULL, 
    QTYSHIPPED          FLOAT            NULL, 
    LOADDATE            DATE             NULL
);

Insert into TEST2567_ENTITY (
SALESORDERNUMBER, SEQNO, LINEITEM, PARTID, PARTNAME, PARTVERSION,
ORIGDATEREQD, CURDATEREQD, CUSTOMERNAME, CUSTORDERNUMBER, ORDERSTATE,
DATECREATED, DATECHANGED, ORIGQTYREQD, CUSTOMERQTYREQD, CURQTYREQD,
PRICEPERPART, QTYSHIPPED, LOADDATE
) values (
'EM71130021', '001', '01', 'PART-30021', 'PART-30021', null, 
to_timestamp('03.01.05','DD.MM.RR HH24:MI:SSXFF'),
to_timestamp('03.01.05','DD.MM.RR HH24:MI:SSXFF'), 'EXTERN', '12701', 'B',
to_timestamp('04.08.03','DD.MM.RR HH24:MI:SSXFF'),
to_timestamp('27.04.04','DD.MM.RR HH24:MI:SSXFF'), 0, 0, 12701,
0, 0, to_timestamp('26.04.04','DD.MM.RR HH24:MI:SSXFF')
);
